/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleLayout: typeof import('./components/Articles/ArticleLayout.vue')['default']
    ArticleList: typeof import('./components/Articles/ArticleList.vue')['default']
    ArticleNav: typeof import('./components/Articles/ArticleNav.vue')['default']
    LandingAbout: typeof import('./components/Landing/LandingAbout.vue')['default']
    LandingNav: typeof import('./components/Landing/LandingNav.vue')['default']
    LandingSocials: typeof import('./components/Landing/LandingSocials.vue')['default']
    LearningToUnitTestEn: typeof import('./components/Articles/Content/learning-to-unit-test-en.md')['default']
    LearningToUnitTestEs: typeof import('./components/Articles/Content/learning-to-unit-test-es.md')['default']
    PDFAbout: typeof import('./components/Resume/PDF/PDFAbout.vue')['default']
    PDFAwards: typeof import('./components/Resume/PDF/PDFAwards.vue')['default']
    PDFBorder: typeof import('./components/Resume/PDF/PDFBorder.vue')['default']
    PDFButtonFloat: typeof import('./components/Resume/PDF/PDFButtonFloat.vue')['default']
    PDFDevIcon: typeof import('./components/Resume/PDF/PDFDevIcon.vue')['default']
    PDFEducation: typeof import('./components/Resume/PDF/PDFEducation.vue')['default']
    PDFExperience: typeof import('./components/Resume/PDF/PDFExperience.vue')['default']
    PDFInterests: typeof import('./components/Resume/PDF/PDFInterests.vue')['default']
    PDFModal: typeof import('./components/Resume/PDF/PDFModal.vue')['default']
    PDFObjective: typeof import('./components/Resume/PDF/PDFObjective.vue')['default']
    PDFSkills: typeof import('./components/Resume/PDF/PDFSkills.vue')['default']
    PDFSkillsRender: typeof import('./components/Resume/PDF/PDFSkillsRender.vue')['default']
    PDFSocials: typeof import('./components/Resume/PDF/PDFSocials.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartAbout: typeof import('./components/Resume/Start/StartAbout.vue')['default']
    StartAwards: typeof import('./components/Resume/Start/StartAwards.vue')['default']
    StartButtonFloat: typeof import('./components/Resume/Start/StartButtonFloat.vue')['default']
    StartDevIcon: typeof import('./components/Resume/Start/StartDevIcon.vue')['default']
    StartEducation: typeof import('./components/Resume/Start/StartEducation.vue')['default']
    StartExperience: typeof import('./components/Resume/Start/StartExperience.vue')['default']
    StartInterests: typeof import('./components/Resume/Start/StartInterests.vue')['default']
    StartNav: typeof import('./components/Resume/Start/StartNav.vue')['default']
    StartObjective: typeof import('./components/Resume/Start/StartObjective.vue')['default']
    StartSkills: typeof import('./components/Resume/Start/StartSkills.vue')['default']
    StartSocials: typeof import('./components/Resume/Start/StartSocials.vue')['default']
  }
}
